### ISSUE TITLE
any plan about this repository ?

### ISSUE THREAD

**Issue by huaxuehuaxue** [ambition119/FlinkSQL#1]
waiting to have a look on version 2.0.0,  any release plan on it? thanks.

**Comment by ambition119** [comment]
已经在写代码了，因为flink1.8版本有大的变动，所以我sql解析那层也在等新版本发布后，预计按照1.7版本开发这个月底可以有初步的版本上线。

**Comment by huaxuehuaxue** [comment]
感谢，期待。 建议多一些使用和集成例子。

**Comment by ambition119** [comment]
> 感谢，期待。 建议多一些使用和集成例子。

学习的话 可以看这个  https://github.com/flink-china/flink-training-course

因为我也是抽时间开发，所以很多功能都没有完善，如果大家愿意的话一起完善

**Comment by huaxuehuaxue** [comment]
> > 感谢，期待。 建议多一些使用和集成例子。
> 
> 学习的话 可以看这个 https://github.com/flink-china/flink-training-course
> 
> 因为我也是抽时间开发，所以很多功能都没有完善，如果大家愿意的话一起完善

谢谢！
